// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWISKS-YyFKvu0qCiVdUrQLnpjuAYh9IE',
    appId: '1:452364672232:web:a321bc50f6689b14d4bd5d',
    messagingSenderId: '452364672232',
    projectId: 'tripease-ace10',
    authDomain: 'tripease-ace10.firebaseapp.com',
    storageBucket: 'tripease-ace10.firebasestorage.app',
    measurementId: 'G-YD2W8CHJDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQDvlEJYlKXnr8wqXbzqG5fLJvNULqCKw',
    appId: '1:452364672232:android:a39ca66cdf6cddc3d4bd5d',
    messagingSenderId: '452364672232',
    projectId: 'tripease-ace10',
    storageBucket: 'tripease-ace10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMyS-PSHkwn4op9nLIp3x6_QAh3cOOe-8',
    appId: '1:452364672232:ios:05c6fe77f541690cd4bd5d',
    messagingSenderId: '452364672232',
    projectId: 'tripease-ace10',
    storageBucket: 'tripease-ace10.firebasestorage.app',
    iosBundleId: 'com.example.tripease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMyS-PSHkwn4op9nLIp3x6_QAh3cOOe-8',
    appId: '1:452364672232:ios:05c6fe77f541690cd4bd5d',
    messagingSenderId: '452364672232',
    projectId: 'tripease-ace10',
    storageBucket: 'tripease-ace10.firebasestorage.app',
    iosBundleId: 'com.example.tripease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWISKS-YyFKvu0qCiVdUrQLnpjuAYh9IE',
    appId: '1:452364672232:web:88a6ddbb47b3afecd4bd5d',
    messagingSenderId: '452364672232',
    projectId: 'tripease-ace10',
    authDomain: 'tripease-ace10.firebaseapp.com',
    storageBucket: 'tripease-ace10.firebasestorage.app',
    measurementId: 'G-0Z0MHNKMWX',
  );
}
